### ISSUE TITLE
[Documentation]: Error in Wizard example code.

### ISSUE THREAD

**Issue by gffloodg** [cloudscape-design/components#1223]
### Description

The wizard example code contains a few minor errors when directly copy/pasting.

1. Link tag variant is capitalised:      
```
steps={[
        {
          title: "Choose instance type",
          info: <Link variant="Info">Info</Link>,
```
should be:
```
          info: <Link variant="info">Info</Link>,
```

2. Input tags are missing value:
```
                  <Input />
```
should be:
```
                  <Input value={""} />
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/components/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/components/issues) for duplicate requests

**Comment by johannes-weber** [comment]
Hi @gffloodg, thanks for your report! We've updated the `Link` variant in the [Wizard example](https://cloudscape.design/components/wizard/?tabId=playground).

The example code is focused on demonstrating the Wizard functionality, that's why the form elements, like the input you pointed, are not attached to any state. I think this is a good opportunity to highlight that in the wizard example.
