### ISSUE TITLE
[Feature Request]: Limit time unit choices in Date Range Picker

### ISSUE THREAD

**Issue by fidel-tensoriot** [cloudscape-design/components#1440]
### Description

We are using the cloudscape date range picker with a relative range value. When users are selecting a custom range they have the following under selection of time "seconds", "minutes", "hours", "weeks", "months", "years". We would like to limit the selection to exclude possibly seconds and years? is this possible? I didn't see anything in the documentation about limiting what is available under the `selection of time`. Below is the link to the component page. 

https://cloudscape.design/components/date-range-picker/?tabId=playground&example=with-relative-range-value

![Screenshot 2023-07-19 at 2 45 32 PM](https://github.com/cloudscape-design/components/assets/97477304/ff9caaa3-e937-469a-b826-3bad5a86d748)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/components/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/components/issues) for duplicate requests

**Comment by gethinwebster** [comment]
This is something that we deliberately didn't make configurable, as it would still be possible to input e.g. 24 months even if the 'year' option was removed - we would recommend making any constraints here via validation rather than configuration.

**Comment by bilalq** [comment]
It makes sense that validation is still needed. However, I would suggest that there is still value in being able to limit down to sensible choices for users. We can look at the AWS X-Ray console as an example where this would be helpful. The maximum time range when querying is 6 hours. The presets they have all cover that, but it's still possible to select days/weeks/months as options. It's especially annoying because the validation only happens after the user fills in the time and hits apply. They're able to go through multiple clicks and keystrokes before the range limitation is surfaced. 

I recognize that their console isn't using the current version of Cloudscape, but the problem is the same.

<img width="627" alt="Screenshot 2023-08-18 at 3 54 01 AM" src="https://github.com/cloudscape-design/components/assets/707147/eb9da491-77c2-46d1-b296-154cc62eb970">

**Comment by emtensoriot** [comment]
I agree that validation is crucial and plays a vital role, but it shouldn't be our only line of defense against user errors. Following UX best practices, preventing errors from occurring in the first place often leads to a smoother and more intuitive user experience.

To highlight a specific scenario for our use case: If a user selects a duration in 'months', and they choose 1 month, we're good to go. But, if they opt for 'years' and input any duration, it will **always** be incorrect given our constraints. Just like bilalq's example with AWS X-Ray, allowing users to pick an option that will inevitably result in an error can be frustrating. Instead of knowingly letting them proceed with an invalid choice and then redirecting them, why not streamline the process and narrow down their choices upfront?

**Comment by rolanday** [comment]
@gethinwebster , is there a way to at least set the default units in selection for custom relative range options? The control currently defaults to minutes and our use case doesn't allow for minutes/seconds duration granularity, and providing seconds and minutes options the list suggests otherwise, and relying on validation adds friction to the UX. Having the unit default to hours will help mitigate. Thank you.

**Comment by gethinwebster** [comment]
We recently release a new feature to allow these units to be specified 🎉 

You can use the [`customRelativeRangeUnits` property](https://cloudscape.design/components/date-range-picker/?tabId=api#property-customRelativeRangeUnits) (e.g. `customRelativeRangeUnits={['hour', 'day']}`) to limit the units that you want to allow for selection.
