### ISSUE TITLE
[Feature Request]: The 'list' attribute for the Input Component.

### ISSUE THREAD

**Issue by yossyX** [cloudscape-design/components#1590]
### Description

I apologize for the lack of research regarding the Autosuggest search icon.
Is it possible to set the 'list' attribute for the 'datalist' on the Input as an alternative?

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/datalist

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/components/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/components/issues) for duplicate requests

**Comment by just-boris** [comment]
Hello!

First of all, closing the issue, does not mean stopping the discussion. You could continue asking questions on #1589 even if it is closed. Anyway, let's continue here.

The design decision was that all components with dropdown lists need to have some visual affordance. Zoom icon was chosen to serve this affordance.

Exposing a `list` property on input is basically a suggestion to "build autosuggest which does not look like autosuggest". This is unlikely to happen because of affordance requirements from above.

**Comment by yossyX** [comment]
Hello! @just-boris

Thank you for the detailed explanation.
I didn't quite understand the rules of the issues before, but since this concerns different components, it does seem like having different titles would make it clearer later on.

Regarding the icon for Autosuggest, I don't quite agree since it signifies search. However, I do understand that discussing it here won't lead to any changes. Thanks!
