### ISSUE TITLE
[Bug]: Table Inline edit trigger close event in modal

### ISSUE THREAD

**Issue by verbeckii** [cloudscape-design/components#1687]
### Browser

Chrome

### Package version

v3.0.416

### React version

v18.2

### Description

Hi

I have table and I'd like to inline edit my column but with one specific - when I click on to edit icon I'd like to open a model window where I can do some editable logic
But if I click everywhere in my modal it will instantly trigger something like onCancelEdit event and unmount my modal

It can be strange why I decided to edit a cell in the modal window - I have two column Customer and Store which depends on each other and I found easiest way to edit it together in modal view

### Reproduction

https://codesandbox.io/s/boring-elion-9hdw28?file=/src/App.js
you can click on Text value column and see that modal window will open, just click inside the window and confirm closing window but I'd like to close the window only by clicking Cancel or Save btns

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/components/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/components/issues) for duplicate problems

**Comment by jperals** [comment]
Hello,

This is not really a use case we support. As the name indicates, "inline" editing is for editing values inline, that is, in the table itself, not somewhere else like in a modal.

I would recommend reconsidering the design. As you say that two columns are related to each other, perhaps it is better to trigger edit per row instead of per cell. For example, using [action buttons](https://cloudscape.design/components/table/?tabId=playground&example=with-action-buttons) or [in-context actions](https://cloudscape.design/components/table/?tabId=playground&example=with-in-context-actions).
