### ISSUE TITLE
[Bug]: Warning when openning and then closing dialog in tests

### ISSUE THREAD

**Issue by JElgar** [cloudscape-design/components#2485]
### Package version

3.0.1335

### React version

18.3.1

### Description

When using test utils dom, opening and then closing a dialog has the following warning `Warning: An update to Transition inside a test was not wrapped in act(...)`. This may be related to https://github.com/cloudscape-design/components/issues/2471?

### Reproduction

```
import { Select } from '@amzn/awsui-components-react';
import wrapper from '@amzn/awsui-components-react/polaris/test-utils/dom';
import { render } from '@testing-library/react';
import { test } from 'vitest';

function TestThing() {
	return (
		<div>
			<Select
				options={[
					{
						description: 'abc',
						value: '123',
					},
				]}
				selectedOption={null}
			/>
		</div>
	);
}

test('thing', async () => {
	const { container } = render(<TestThing />);
	const select = wrapper(container).findSelect()!;
	select.openDropdown();
	select.closeDropdown();
});

```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/components/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/components/issues) for duplicate problems

**Comment by MathiasSM** [comment]
They seem to be correctly wrapped for both [current version](https://github.com/cloudscape-design/components/blob/d2c601912b8d6ecc0a001549eecc52600996895b/src/test-utils/dom/internal/dropdown-host.ts#L41-L65) and [your version](https://github.com/cloudscape-design/components/blob/d708896775df56ecef13f1d94f223e75b8fc0460/src/test-utils/dom/internal/dropdown-host.ts#L39-L63) (keep in mind [SelectWrapper](https://github.com/cloudscape-design/components/blob/main/src/test-utils/dom/select/index.ts) extends that class)

Could it be because of the async test callback? (I don't think it should affect it but no idea)

For maintainers: I wonder if [this test](https://github.com/cloudscape-design/components/blob/de1d76be8e8115106ae6d4f0af9a189e579d0893/src/select/__tests__/select.test.tsx#L77-L83) has the same issue?


_Disclaimer: I'm not a mantainer for this package_

**Comment by gethinwebster** [comment]
We are continuing to investigate fixing this internally, but as a workaround, you can get rid of the warnings by wrapping open/close dropdown actions in an _async_ `act` call:

```
test('thing', async () => {
	const { container } = render(<TestThing />);
	const select = wrapper(container).findSelect()!;
	await act(async () => select.openDropdown()};
	await act(async () => select.closeDropdown()};
});
```

**Comment by JElgar** [comment]
Thanks @gethinwebster. That work around works! Head us that Ive also observed this issue with dialogs. Would it make sense to keep this issue open until a fix is released or is that not how you do things around here?

**Comment by taheramr** [comment]
Hello, 

We recently created a fix that will let you use our test utils without the need to wrap it with `act` or `async act`.

You can now remove these wrappers with the latest update from our components package.

Related PRs that fixed this:
- https://github.com/cloudscape-design/component-toolkit/pull/104
- https://github.com/cloudscape-design/component-toolkit/pull/103
