### ISSUE TITLE
[Feature Request]: Select / Autosuggest in table cell

### ISSUE THREAD

**Issue by nicolaeClichici** [cloudscape-design/components#511]
### Description

Hello! 
Is there a way to integrate Select in Table cell ?
I mean, now Select in cell is not working cause of being in cell scope and Select z-index is lower than cell.

Example: 
https://codesandbox.io/s/nostalgic-galileo-cwvcgh?file=/src/App.tsx

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/components/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/components/issues) for duplicate requests

**Comment by connorlanigan** [comment]
The Table component is intended for viewing, rather than editing. For editing data, we recommend to take the user to a dedicated editing page for that resource. You can find more information in [our article about our "Edit resource" pattern](https://cloudscape.design/patterns/resource-management/edit/), including flow charts of the intended navigation flows.

**Comment by nicolaeClichici** [comment]
wow, I'm dumb, sorry and thx.
