### ISSUE TITLE
Highlighted link on side navigation is not attached to font style

### ISSUE THREAD

**Issue by shanayau** [cloudscape-design/components#695]
### Describe the bug

As seen in attachment below, the highlighted link on the side navigation is not attached to a font style. 
![image](https://user-images.githubusercontent.com/123783898/216190107-7f55e412-c334-4dfb-9c95-e3be7a6b1f0a.png)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/components/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/components/issues) for duplicate requests

**Comment by aszuchie** [comment]
Hey, thanks for your feedback. Added this to our backlog.

**Comment by shanayau** [comment]
> Hey, thanks for your feedback. Added this to our backlog.

Thanks for adding this to your backlog. I see the last update to Figma design system was 7 months. How soon do you estimate an update for this?

**Comment by linluiux** [comment]
Hey, thank you so much for spotting it and sorry for replying late! Regarding figma resource updates, we update Figma resources approx. every 6 months. We are working on a new updated version right now. You will see a new version soon. 

For this issue specifically, I am checking it and will get back to you.

**Comment by linluiux** [comment]
Hey, what you found in the system is intentional made in Figma. We wanted to keep the line-height of that navigation item same as the line-height of Body paragraph that’s used for the normal state which is 22px. Currently we don't have 14px/22px line height in heavy font style as a defined style in Figma as it is not very commonly used as the other ones. 

When in implementation, developers need to specify the three types of specs, which are font style, font weight and line height each. You can inspect these values from Figma file and they are accurate.
