### ISSUE TITLE
[Documentation]: Custom Tutorial

### ISSUE THREAD

**Issue by url54** [cloudscape-design/components#823]
### Description

While the demos are fantastic, they don't really show how to put-together the different components into a customizable application. It would be nice to have a small tutorial that showed creating a new single page application with a few components, and some of the visual design features (light-dark-mode). So that we can understand better how to pull and put all the pieces together. 

Currently, I am trying to create an application to replace a current aging application, and I love the Cloudscape design pieces. I just want to ensure that I get the most out of everything that is offered. (Like right now I have no idea how to ensure light/dark-mode, compact/comfortable modes are initialized across all the pages, or even how to use them on a single page) So things like that would be excellent to see through a process of building a small application.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/components/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/components/issues) for duplicate requests

**Comment by connorlanigan** [comment]
Hi, thank you for reaching out. Happy to hear that you like the demos/examples!
Just to clarify, there are two types of code available: playground examples for each component ([for example the Table](https://cloudscape.design/components/table/?tabId=playground)), and [demos that put the components together in a full page](https://cloudscape.design/demos/overview/). For the latter, you can find their source code through the link in the top right of the page, or by visiting the [`demos`](https://github.com/cloudscape-design/demos) repository directly. Unfortunately, the code that is used there for toggling the visual modes is currently not available, because these toggles are built in a way that is specific to these demos.

There is [a self-paced workshop available on how to build an application with Cloudscape](https://catalog.us-east-1.prod.workshops.aws/workshops/5b7fe737-7ea2-4c4d-b572-76df6adabd47), but it does not cover building such toggles. Our website includes [documentation on the helper functions that you can use to control light/dark mode and the content density](https://cloudscape.design/get-started/integration/global-styles/#manipulate-global-styles-using-js-helpers).

**Comment by url54** [comment]
Hello,

Thank you for the message. I will definitely give the workshop a go. Do you happen to have an internal to AWS workshop as well?

But thank you for the message!

**Comment by connorlanigan** [comment]
I can't share any internal resources. Is there anything specific you're looking for?

**Comment by hiimnhan** [comment]
@connorlanigan is there any demo or tutorial on Theming. The documentation is not quite clear and seems like everyone has some troubles with that.

**Comment by just-boris** [comment]
This will be addressed as a part of a bigger task https://github.com/cloudscape-design/components/issues/588
